### ISSUE TITLE
Some user stats for the institutional portal of 'Het Natuurhistorisch' would be appreciated.

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-nhm-rotterdam#5]
Some user stats for the institutional portal of 'Het Natuurhistorisch' would be appreciated.

_Originally posted by @nielsraes in https://github.com/gbif/hp-north-america/issues/3#issuecomment-801771600_

**Comment by MortenHofft** [comment]
Hi @nielsraes you had accidentally commented on an issue in the north american repository. You can add Google Analytics to the Het Musem website as well. Let me know if you need help in doing so. It is documented how to here https://hp-theme.gbif-staging.org/measurements

**Comment by langeveldNMR** [comment]
We are currently looking into using Google Analytics
